version: "3.8"

services:
    # Laravel App Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - "./:/var/www"
            - "./php.ini:/usr/local/etc/php/php.ini"
        networks:
            - sail

    # Nginx Web Server Service
    webserver:
        image: "nginx:latest"
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - "./:/var/www"
            - "./nginx.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - app
            - db
        networks:
            - sail

    # MySQL Database Service
    db:
        image: "mysql:latest"
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: bengkel_ongel
            MYSQL_PASSWORD: password
        volumes:
            - "dbdata:/var/lib/mysql"
        networks:
            - sail
        ports:
            - "3306:3306"

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PASSWORD: password
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - sail

    # Vite Dev Server Service
    vite:
        image: node:16
        container_name: vite_dev
        working_dir: /var/www
        volumes:
            - "./:/var/www"
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    dbdata:
        driver: local
